name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - run: chmod +x convert.sh
    - run: convert.sh > substitutions.js

    - name: Upload build artifact
      uses: actions/upload-artifact@v7
      with:
        path: substitutions.js
        archive: false
        name: substitutions.js
        if-no-files-found: error
